### ISSUE TITLE
[FEATURE] 상세 페이지 마크업 및 스타일링

### ISSUE THREAD

**Issue by hardy-is-cat** [LikeLion-FE-Final-Project03/car-zip#17]
## 🌳 작업 브랜치

feat/#17

## 📝 TASK 개요
상세페이지의 마크업과 스타일링을 완성합니다.

## ✅ TO DO 및 진행현황

- [x] 뒤로가기 버튼 있는 상태바
- [x] 페이지 타이틀+즐겨찾기 버튼
- [x] 주차장 키워드 태그
- [x] 주차장 주소, 복사버튼
- [x] 주차장 기본 요금 및 추가 시간당 요금
- [x] 주차요금 미리 계산 버튼
- [x] 전화 버튼
- [x] 길 안내 버튼(데스크탑-카카오맵 길찾기, 모바일-카카오맵 어플 길찾기)
- [x] 이용요금 ~ 부가시설 
- [x] 최근 업데이트 날짜
