### ISSUE TITLE
[FEATURE] 메인화면 지도 관련 기능

### ISSUE THREAD

**Issue by Juhee-Hwang** [LikeLion-FE-Final-Project03/car-zip#20]
## 🌳 작업 브랜치

`feature/#20`

## 📝 TASK 개요

메인화면에서 카카오지도 API 연결 후 지도 관련 작업할 예정입니다.

## ✅ TO DO 및 진행현황

- [x] 카카오지도 API 연결
- [x] 지도 비율 확대 축소 기능
- [x] 현위치로 이동하는 버튼
- [x] 메인화면 간단한 마크업
