### ISSUE TITLE
[FEATURE] 주차장 선택 시 해당 주차장의 바텀 시트 띄우기

### ISSUE THREAD

**Issue by Juhee-Hwang** [LikeLion-FE-Final-Project03/car-zip#47]
## 🌳 작업 브랜치

`feature/#47`

## 📝 TASK 개요
- 주차장 선택 시 해당 주차장 바텀 시트 띄우기
- 참고 : https://apis.map.kakao.com/web/sample/markerWithInfoWindow/

## ✅ TO DO 및 진행현황
- [x] 바텀 시트 마크업
- [x] 주차장 정보 받아오기
- [x] 주차장 정보 뿌려주기
- [x] 위치 기준 주변 주차장 마크 뿌려주기
