### ISSUE TITLE
[FEATURE] 주차장 데이터를 가져와 상세페이지에 붙이기

### ISSUE THREAD

**Issue by hardy-is-cat** [LikeLion-FE-Final-Project03/car-zip#58]
## 🌳 작업 브랜치

`feat/#58`

## 📝 TASK 개요
- 실제 데이터를 받아와 상세페이지에 붙여주기

## ✅ TO DO 및 진행현황
- [x] 주차장 데이터 가져오기
- [x] 가져온 주차장 데이터를 상세페이지에 출력
- [x] 이전 페이지에서 어떤 값을 눌렀는지 전달받을 수 있는 방법 찾기
- [x] 주차비 미리보기 페이지로 데이터 전달
- [x] 주차비 미리보기 페이지에 주차 요금 정보 출력
