### ISSUE TITLE
[FEATURE] 파이어베이스와 고객 즐겨찾기 데이터 연동

### ISSUE THREAD

**Issue by hardy-is-cat** [LikeLion-FE-Final-Project03/car-zip#66]
## 🌳 작업 브랜치
feat/#66

## 📝 TASK 개요
고객의 즐겨찾기 데이터를 만들고 데이터를 토대로 즐겨찾기 기능 추가

## ✅ TO DO 및 진행현황

- [x] 로그인시 고객의 즐겨찾기 데이터가 파이어베이스에 생성(이미 있다면 X)
- [x] 상세페이지 진입시 고객의 데이터베이스 즐겨찾기 배열에 해당 주차장 코드가 있으면 즐겨찾기 버튼 활성화
- [x] 비활성화 된 즐겨찾기 버튼을 누르면 고객의 데이터 베이스 즐겨찾기 배열에 주차장 코드 추가
- [x] 활성화 된 즐겨찾기 버튼을 누르면 고객의 데이터 베이스 즐겨찾기 배열의 주차장 코드 삭제
