### ISSUE TITLE
[FEATURE] 배포를 위한 빌드

### ISSUE THREAD

**Issue by s-ja** [LikeLion-FE-Final-Project03/car-zip#69]
## 🌳 작업 브랜치

feat/#67

`type/#issueNum`

## 📝 TASK 개요

프로젝트 완성후 배포를 위한 빌드 테스트 및 호스팅
[vite 툴체인을 이용한 빌드와 여러 배포 방법](https://vitejs-kr.github.io/guide/static-deploy.html
)
## ✅ TO DO 및 진행현황

- [ ] vite 툴체인을 이용한 빌드
- [ ] 도메인 확보
- [ ] 호스팅을 통한 서버 업로드
- [ ] 기능 확인 및 테스트
