### ISSUE TITLE
[FEATURE] 상세페이지에 리뷰 컴포넌트 연결

### ISSUE THREAD

**Issue by hardy-is-cat** [LikeLion-FE-Final-Project03/car-zip#73]
## 🌳 작업 브랜치
feat/#

## 📝 TASK 개요
리뷰 데이터를 가져와 상세페이지에 노출시킵니다

## ✅ TO DO 및 진행현황
- [ ] 리뷰 컴포넌트 가져오기
- [ ] 리뷰 컴포넌트를 스와이퍼로 만들기
- [ ] 확인할 수 있는 리뷰의 최대 개수를 제한
