### ISSUE TITLE
[FEATURE] 리얼타임 데이터베이스 이용하여 주차장 정보 불러오기

### ISSUE THREAD

**Issue by hardy-is-cat** [LikeLion-FE-Final-Project03/car-zip#85]
## 🌳 작업 브랜치

feat/#

## 📝 TASK 개요
- 공공데이터 api가 아닌 파이어베이스 리얼타임 데이터베이스에서 주차장 정보를 불러옵니다

## ✅ TO DO 및 진행현황

- [ ] 리얼타임 데이터베이스에서 데이터 불러오기
- [ ] 불러온 데이터베이스에서 주차장 코드를 리뷰 컴포넌트에 props로 전달해주기
- [ ] 리뷰 작성 버튼 컴포넌트에 주차장 코드를 props로 전달해주기
- [ ] 상위페이지에서 주차장 코드 받기
